services:
  postgres:
    image: postgres:16-alpine
    container_name: conduct_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: conduct_user
      POSTGRES_PASSWORD: conduct_pass
      POSTGRES_DB: conduct_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: