[build]
builder = "nixpacks"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[build.nixpacksPlan.phases.install]
cmds = ["npm install"]

[build.nixpacksPlan.phases.build]
cmds = [
  "npx prisma generate",
  "npm run build"
]

[deploy]
startCommand = "npx prisma migrate deploy && node dist/main"
healthcheckPath = "/api/v1"
restartPolicyType = "on_failure"